- name: bug
  description: Something isn't working
  color: 000000
- name: enhancement
  description: New feature or request
  color: 000000
- name: question
  description: Further information is requested
  color: 000000
- name: security
  color: 000000
  description: Security bug
- name: todo
  color: 000000
  description: Todo list
- name: documentation
  description: Improvements or additions to documentation
  color: 000000
- name: bugfix
  description: Something wasn't working, but is now because of this fix
  color: 000000
- name: duplicate
  description: This issue or pull request already exists
  color: ffffff
- name: help wanted
  description: Extra attention is needed
  color: 000000
- name: invalid
  description: This doesn't seem right
  color: ffffff
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: autolocked
  description: Automatically locked by an action
  color: 000000
- name: npm
  color: 000000
  description: NPM update
- name: dependencies
  color: 000000
  description: Dependency update
- name: meta
  color: 000000
  description: GitHub or repository-related changes
- name: codeclimate
  color: 000000
  description: Issues auto-generated by CodeClimate
- name: dependabot
  color: 000000
  description: PRs opened by Dependabot
- name: release
  color: 000000
  description: A release of the bot
- name: autogenerated
  color: 000000
  description: An automatically generated issue or PR
- name: stale
  color: ffffff
  description: No one seems to be touching this anymore...
- name: pinned
  color: 000000
  description: This is important, look at it
- name: 🚧 WIP
  color: FBCA04
  description: Still work-in-progress, please don't review and don't merge
- name: ✅ Approved
  color: 0E8A16
  description: Pull Request has been approved and can be merged
- name: 🌟 Needs more Approvals
  color: 96C823
  description: Pull Request needs more approvals
- name: ⚠️ Changes requested
  color: AA2626
  description: Pull Request needs changes before it can be reviewed again
- name: ✨ Merged
  color: 6F42C1
  description: Pull Request has been merged successfully
- name: close
  color: 000000
  description: Marked for closure
- name: merge when passing
  color: 000000
  description: Automatically merge
- name: fixed
  color: 00ff00
  description: Bug fixed
- name: implemented
  color: 000000
  description: Feature implemented
  name: 🔍 Ready for Review
  color: 334796
  description: Pull Request is not reviewed yet
- name: style
  color: 000000
  description: Changes that do not affect the meaning of the code
- name: refactor
  color: 000000
  description: A code change that neither fixes a bug nor adds a feature
- name: performance
  color: 000000
  description: A code change that improves performance